export default services = [
  { key: 'EC2', value: 'Amazon EC2', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Compute_AmazonEC2.png' },
  { key: 'S3', value: 'Amazon S3', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Storage_AmazonS3_bucket.png' },
  { key: 'RDS', value: 'Amazon RDS', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Database_AmazonRDS.png' },
  { key: 'SQS', value: 'Amazon SQS', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Messaging_AmazonSQS.png' },
  { key: 'DYNAMO_DB', value: 'Amazon DynamoDB', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Database_AmazonDynamoDB.png' },
  { key: 'LAMBDA', value: 'AWS Lambda', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Compute_AWSLambda.png' },
  { key: 'VPC', value: 'Amazon VPC', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Compute_AmazonVPC.png' },
  { key: 'CLOUDFORMATION', value: 'AWS CloudFormation', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/ManagementTools_AWSCloudFormation.png' },
  { key: 'CLOUDFRONT', value: 'CloudFront', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/NetworkingContentDelivery_AmazonCloudFront.png' },
  { key: 'ROUTE_53', value: 'Amazon Route 53', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/NetworkingContentDelivery_AmazonRoute53.png' },
  { key: 'GLACIER', value: 'Amazon Glacier', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Storage_AmazonGlacier.png' },
  { key: 'KINESIS', value: 'Amazon Kinesis', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Analytics_AmazonKinesis.png' },
  { key: 'STORAGE_GATEWAY', value: 'Storage Gateway', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Storage_AWSStorageGateway.png' },
  { key: 'ECS', value: 'ECS', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Compute_AmazonECS.png' },
  { key: 'ELASTICACHE', value: 'Amazon ElastiCache', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Database_AmazonElasticCache.png' },
  { key: 'ELASTIC_BEANSTALK', value: 'Amazon Elastic Beanstalk', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Compute_AWSElasticBeanstalk.png' },
  { key: 'IAM', value: 'IAM', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/SecurityIdentityCompliance_AWSIAM.png' },
  { key: 'SNS', value: 'Amazon Simple Notification Service', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Messaging_AmazonSNS.png' },
  { key: 'SES', value: 'Amazon Simple Email Service', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/Messaging_AmazonSES.png' },
  { key: 'STEP_FUNCTIONS', value: 'AWS Step Functions', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/ApplicationServices_AWSStepFunctions.png' },
  { key: 'API_GATEWAY', value: 'API Gateway', imageUrl : 'https://s3.amazonaws.com/aws-icons-woo/ApplicationServices_AmazonAPIGateway.png' },
]
